GET http://localhost:8080/user HTTP/1.1

###
GET http://localhost:8080/user/1 HTTP/1.1

###
POST http://localhost:8080/user HTTP/1.1
content-type: application/json

{
    "username": "newuser",
    "password": "password123",
    "email": "newuser@example.com"
}

###
PUT http://localhost:8080/user/1 HTTP/1.1
content-type: application/json

{
    "username": "updateduser",
    "password": "newpassword",
    "email": "updateduser@example.com"
}

###
DELETE http://localhost:8080/user/1 HTTP/1.1